/* Desktop writing, discovery and recoverable workspace tools. */
(function(){
'use strict';
const E=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const W=()=>window.ChenNanDocumentWorkspace,C=()=>window.ChenNanCloud,H=()=>window.ChenNanWritingHistory;
let lastCloudSave=null,searchTimer;
function modal(title,body){let d=E('desktopDialog');if(!d){d=document.createElement('dialog');d.id='desktopDialog';d.className='desktop-dialog';document.body.appendChild(d)}d.innerHTML='<div class="panel-head"><h2>'+esc(title)+'</h2><button class="btn ghost small" data-close>关闭</button></div>'+body;d.querySelector('[data-close]').onclick=()=>d.close();if(!d.open)d.showModal();return d}
function error(d,e){const p=d.querySelector('[role=alert]');if(p)p.textContent=e.message||String(e);else toast(e.message||String(e))}
function download(payload,name){const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportWorkspace(){W()?.saveDraft();download({format:'chennan-workspace-backup',schemaVersion:1,createdAt:new Date().toISOString(),payload:db},'chennan-backup-'+new Date().toISOString().slice(0,10)+'.json')}
function history(){
 W().saveDraft();const date=W().date,list=db.documentHistory?.[date]||[];
 const d=modal('历史版本 · '+date,'<p>自动版本最多每分钟一份，每日保留最近20份，总历史容量1.2 MB。恢复后仍可找回恢复前的稿件。</p><div class="actions"><button id="checkpointNow" class="btn primary">保留当前版本</button></div><div id="versionList"></div><p role="alert"></p>');
 d.querySelector('#checkpointNow').onclick=()=>{H().checkpoint(db,date,db.dailyDocs[date],'手动保留');save();history()};
 d.querySelector('#versionList').innerHTML=list.map((v,i)=>'<button class="version-row" data-version="'+i+'"><b>'+esc(new Date(v.createdAt).toLocaleString())+'</b><span>'+esc(v.reason)+' · '+esc(v.document.title||'无标题')+' · '+v.document.content.length+' 字</span></button>').join('')||'<p>尚无历史版本。编辑现有内容或点击“保留当前版本”即可创建。</p>';
 d.querySelectorAll('[data-version]').forEach(b=>b.onclick=()=>{const v=list[Number(b.dataset.version)],diff=H().compare(v.document.content,db.dailyDocs[date].content);modal('版本对比','<p>旧版本：'+esc(new Date(v.createdAt).toLocaleString())+'，前 '+diff.unchanged+' 行未改。</p><div class="version-compare"><section><h3>旧版本变化部分</h3><pre>'+esc(diff.removed||'无')+'</pre></section><section><h3>当前变化部分</h3><pre>'+esc(diff.added||'无')+'</pre></section></div><div class="actions"><button id="restoreDocument" class="btn primary">恢复此版本</button><button id="backHistory" class="btn ghost">返回列表</button></div>');E('backHistory').onclick=history;E('restoreDocument').onclick=()=>{if(!confirm('恢复此版本？当前稿件会先保留为历史版本。'))return;W().restore(v.document);E('desktopDialog').close();toast('版本已恢复，正在同步')}});
}
function memoryExtra(pid){
 const p=person(pid),host=E('memoryPerson');if(!p||!host)return;
 host.querySelector('.memory-extra')?.remove();const box=document.createElement('div');box.className='memory-extra';
 const data=db.characterNotes?.[pid]||{relations:'',foreshadowing:''};
 box.innerHTML='<details open><summary>关系与待完成伏笔</summary><label>人物关系<textarea id="memoryRelations" rows="2" placeholder="例如 C.02 是姐姐；C.18 是同事">'+esc(data.relations)+'</textarea></label><label>未完成伏笔<textarea id="memoryForeshadowing" rows="2" placeholder="记录需要继续回应的事件">'+esc(data.foreshadowing)+'</textarea></label><button class="btn ghost small" id="ackGrowth">本段变化合理，不再提醒</button><small>只确认当前文本的提示；修改内容后会重新检查。</small></details>';
 host.appendChild(box);box.querySelectorAll('textarea').forEach(t=>t.oninput=()=>{db.characterNotes=db.characterNotes||{};db.characterNotes[pid]={relations:box.querySelector('#memoryRelations').value,foreshadowing:box.querySelector('#memoryForeshadowing').value};save()});box.querySelector('#ackGrowth').onclick=()=>{W().acknowledge(pid);toast('已确认当前段落的变化')};
}
function focusMode(){const section=E('novel');section.classList.toggle('writing-focus');E('writingFocus').textContent=section.classList.contains('writing-focus')?'退出专注':'专注写作';}
function setWidths(){const layout=document.querySelector('.daily-doc-layout');if(!layout)return;let widths;try{widths=JSON.parse(localStorage.getItem('chennan-writing-widths')||'{}')}catch(_){widths={}};const left=widths.left||150,right=widths.right||290;layout.style.setProperty('--writing-left',left+'px');layout.style.setProperty('--writing-right',right+'px');const panels=[document.querySelector('.speech-panel'),document.querySelector('.memory-panel')];panels.forEach((panel,i)=>{const grip=document.createElement('div');grip.className='writing-resizer '+(i?'right':'left');grip.tabIndex=0;grip.role='separator';grip.setAttribute('aria-label',i?'调整记忆侧栏宽度':'调整人物侧栏宽度');grip.setAttribute('aria-orientation','vertical');panel.appendChild(grip);const adjust=value=>{const key=i?'right':'left';widths[key]=Math.max(i?230:120,Math.min(i?380:240,value));layout.style.setProperty('--writing-'+key,widths[key]+'px');localStorage.setItem('chennan-writing-widths',JSON.stringify(widths));};grip.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();adjust((widths[i?'right':'left']||(i?right:left))+(e.key==='ArrowRight'?10:-10)*(i?-1:1))}};grip.onpointerdown=e=>{e.preventDefault();const start=e.clientX,initial=panel.getBoundingClientRect().width;grip.setPointerCapture(e.pointerId);grip.onpointermove=ev=>adjust(initial+(ev.clientX-start)*(i?-1:1));grip.onpointerup=()=>grip.onpointermove=null;};});}
function search(q){
 q=String(q||'').trim().toLowerCase();if(!q)return [];const results=[],matches=s=>String(s||'').toLowerCase().includes(q),push=(kind,title,text,action)=>{if(results.length<80)results.push({kind,title,text,action})};
 db.people.filter(p=>matches(pCode(p)+' '+p.name+' '+JSON.stringify(p.personality||{})+' '+JSON.stringify(db.characterNotes?.[p.id]||{}))).forEach(p=>push('人物',pCode(p)+' · '+p.name,p.personality?.summary||'',()=>{go('people');E('personSearch').value=pCode(p);E('personSearch').dispatchEvent(new Event('input',{bubbles:true}));W().selectPerson(p.id)}));
 Object.entries(db.dailyDocs||{}).forEach(([date,d])=>{if(matches(d.title+' '+d.content))push('文档',date+' · '+(d.title||'每日文档'),d.content,()=>{go('novel');W().openDate(date);highlight(q)})});
 db.records.forEach(r=>{if(matches(r.title+' '+r.content))push('事件',r.date+' · '+(r.title||r.type),r.content,()=>{go('records');E('recordPerson').value=r.personId;E('recordType').value='all';E('recordSearch').value=r.title||r.content;E('recordSearch').dispatchEvent(new Event('input',{bubbles:true}));})});
 (db.portfolio?.holdings||[]).forEach(h=>{if(matches(JSON.stringify(h)))push('交易',h.symbol+' · '+(person(h.personId)?.name||h.personId),h.quantity+'股 · '+(h.status==='sold'?'已卖出':'持有中'),()=>{go('holdingsV2');const target=[...document.querySelectorAll('.batch-card')].find(x=>x.textContent.includes(h.symbol));target?.scrollIntoView({block:'center'});})});
 return results;
}
function highlight(q){const walker=document.createTreeWalker(E('dailyEditor'),NodeFilter.SHOW_TEXT);let n;while((n=walker.nextNode())){const at=n.textContent.toLowerCase().indexOf(q);if(at>=0){const range=document.createRange();range.setStart(n,at);range.setEnd(n,at+q.length);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);n.parentElement.scrollIntoView({block:'center'});E('dailyEditor').focus();break;}}}
function showSearch(q=''){const d=modal('全局搜索','<label>人物、正文、事件、交易<input id="workspaceQuery" class="input" placeholder="输入关键字…" value="'+esc(q)+'"></label><div id="workspaceResults"></div>');const input=d.querySelector('input');const show=()=>{const list=search(input.value);E('workspaceResults').innerHTML=list.map((r,i)=>'<button class="version-row" data-result="'+i+'"><b>'+esc(r.kind+' · '+r.title)+'</b><span>'+esc(r.text.slice(0,180))+'</span></button>').join('')||'<p>输入关键字，最多显示80条匹配结果。</p>';d.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{d.close();list[Number(b.dataset.result)].action()});};input.oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(show,120)};show();input.focus();}
async function restorePayload(raw,d){const payload=H().validateBackup(raw);if(!confirm('恢复 '+payload.people.length+' 位人物、'+Object.keys(payload.dailyDocs).length+' 份文档？当前工作区会先创建云端备份。'))return;W().saveDraft();await C().flush(true);await C().createBackup('恢复前备份');await C().replaceWorkspace(payload);d.close();toast('恢复完成，已保存到云端');}
async function backupCenter(){
 W().saveDraft();const d=modal('备份与恢复','<div class="notice">最近云端保存：'+esc(lastCloudSave?new Date(lastCloudSave).toLocaleString():'本次会话尚未确认')+' · 待同步工作区：'+(C().pending()?1:0)+'</div><div class="actions"><button class="btn primary" id="exportWorkspace">完整导出</button><button class="btn ghost" id="createBackup">创建云端备份</button><label class="btn ghost">导入恢复<input id="importWorkspace" type="file" accept=".json,application/json" hidden></label></div><p>云端每天首次修改前自动保留一份快照，保留最近30份。定期下载完整导出文件到电脑，可独立于云端恢复。导出不包含登录凭证。</p><p role="alert"></p><div id="backupRows">正在加载云端备份…</div>');
 d.querySelector('#exportWorkspace').onclick=exportWorkspace;
 d.querySelector('#createBackup').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{await C().flush(true);await C().createBackup('手动备份');if(d.open)backupCenter()}catch(e){error(d,e);b.disabled=false}};
 d.querySelector('#importWorkspace').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>6000000)throw new Error('文件超过6 MB');await restorePayload(JSON.parse(await f.text()),d)}catch(e){error(d,e)}};
 const backupRows=d.querySelector('#backupRows');
 try{const r=await C().listBackups();backupRows.innerHTML=r.backups.map(b=>'<div class="backup-row"><div><b>'+esc(new Date(b.created_at).toLocaleString())+'</b><small>'+esc(b.label)+' · 版本 '+b.version+'</small></div><button class="btn ghost small" data-download="'+esc(b.id)+'">下载</button><button class="btn ghost small" data-restore="'+esc(b.id)+'">恢复</button></div>').join('')||'<p>尚无云端备份，可点击“创建云端备份”。</p>';backupRows.querySelectorAll('[data-download]').forEach(b=>b.onclick=async()=>{try{const r=await C().getBackup(b.dataset.download);download({format:'chennan-workspace-backup',schemaVersion:1,payload:r.backup.payload},'chennan-cloud-backup.json')}catch(e){error(d,e)}});backupRows.querySelectorAll('[data-restore]').forEach(b=>b.onclick=async()=>{try{const r=await C().getBackup(b.dataset.restore);await restorePayload(r.backup.payload,d)}catch(e){error(d,e)}});}catch(e){backupRows.textContent='无法读取云端备份；完整导出仍可使用。';error(d,e)}
}
const actions=E('novel')?.querySelector('.topbar .actions');if(actions){actions.insertAdjacentHTML('afterbegin','<button class="btn ghost" id="writingHistory">历史版本</button><button class="btn ghost" id="writingFocus">专注写作</button>');E('writingHistory').onclick=history;E('writingFocus').onclick=focusMode;setWidths()}
const header=document.querySelector('.header-right');if(header){const b=document.createElement('button');b.id='workspaceBackup';b.className='btn ghost small';b.textContent='备份恢复';b.onclick=backupCenter;header.prepend(b)}
const searchInput=E('globalPersonSearch');if(searchInput){searchInput.placeholder='全局搜索 · Ctrl+K';searchInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopImmediatePropagation();showSearch(searchInput.value)}},true)}
document.addEventListener('chennan:memory-person',e=>memoryExtra(e.detail.personId));
document.addEventListener('chennan:cloud-ready',e=>{lastCloudSave=e.detail?.updatedAt||null});document.addEventListener('chennan:cloud-saved',e=>lastCloudSave=e.detail?.updatedAt||new Date().toISOString());
document.addEventListener('keydown',e=>{if(!C().hydrated||(!e.ctrlKey&&!e.metaKey))return;const k=e.key.toLowerCase();if(k==='k'){e.preventDefault();showSearch()}if(k==='s'&&E('novel').classList.contains('active')){e.preventDefault();W().saveDraft();C().flush(true).catch(err=>toast(err.message))}if(e.shiftKey&&k==='f'&&E('novel').classList.contains('active')){e.preventDefault();focusMode()}if(e.shiftKey&&k==='h'&&E('novel').classList.contains('active')){e.preventDefault();history()}});
window.ChenNanDesktopTools={history,search,backupCenter,exportWorkspace};
})();
