/* Real login and cloud operations. No auth overlay removal, storage seeding, or db injection. */
const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
const URL=process.env.E2E_URL||'https://dalulu05168.github.io/growth-story-workspace/';
const creds=JSON.parse(fs.readFileSync(process.env.E2E_CREDENTIALS||'/tmp/chennan-e2e.json'));
assert.match(creds.username,/^e2e_/,'Only disposable E2E accounts may modify business data');
const endpoint='https://afelbznpwltuebmqmqbh.supabase.co/functions/v1/workspace-cloud';
const key='sb_publishable_J548-tZcZAxnUF4HD-VPEA_Gepy26Ec';
fs.mkdirSync('evidence',{recursive:true});const results=[],errors=[],responses=[];let token='',browser,page;
async function step(name,steps,expected,fn){try{const actual=await fn();results.push({name,steps,expected,actual:actual??'Assertions satisfied',status:'PASS'});console.log('PASS '+name)}catch(e){results.push({name,steps,expected,actual:e.message,status:'FAIL'});throw e}finally{fs.writeFileSync('evidence/results.json',JSON.stringify({url:URL,results,errors,responses},null,2))}}
async function cloud(action,payload={},session=token){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+session},body:JSON.stringify({action,...payload})});const data=await r.json();responses.push({action,status:r.status,ok:data.ok,version:data.version,code:data.code,people:data.payload?.people?.length,records:data.payload?.records?.length,holdings:data.payload?.portfolio?.holdings?.length});assert.equal(r.status,200,JSON.stringify(data));return data}
async function stored(predicate){let data;for(let i=0;i<35;i++){data=await cloud('load');if(predicate(data.payload))return data.payload;await new Promise(r=>setTimeout(r,300))}assert.fail('Cloud state did not meet expected condition')}
async function login(p){await p.goto(URL,{waitUntil:'networkidle'});await p.locator('#loginForm input[name=user]').fill(creds.username);await p.locator('#loginForm input[name=password]').fill(creds.password);const response=p.waitForResponse(r=>r.url()===endpoint&&r.request().postDataJSON()?.action==='login');await p.locator('#loginForm button').click();const data=await(await response).json();assert.equal(data.ok,true,data.error);token=data.token;await p.locator('.app.app-ready').waitFor({state:'visible',timeout:25000});await p.locator('#authRoot').waitFor({state:'hidden'})}
async function nav(id){await page.locator('.nav button[data-page="'+id+'"]').click();await page.locator('#'+id+'.active').waitFor({state:'visible'})}
async function modalSave(){await page.locator('#modalForm .modal-foot .primary').click();await page.locator('#modal').waitFor({state:'hidden'})}
async function date(day){await page.locator('#dailyDatePicker').fill(day);await page.locator('#openDate').click()}
async function write(text){await page.locator('#dailyEditor').fill(text);await page.locator('#saveDaily').click()}
(async()=>{
 browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('status of 401'))errors.push(m.text())});page.on('dialog',d=>d.accept());
 await step('登录页与错误登录','打开网址，提交错误凭据','账号密码表单；拒绝错误登录；无验证码',async()=>{await page.goto(URL,{waitUntil:'networkidle'});assert.equal(await page.locator('#loginForm input[name=user]').inputValue(),'chennan118');assert.equal(await page.locator('input[type=password]').count(),1);assert.equal(await page.locator('input[name*=otp]').count(),0);await page.locator('#loginForm input[name=user]').fill('invalid_'+Date.now());await page.locator('#loginForm input[name=password]').fill('invalid');await page.locator('#loginForm button').click();await page.waitForFunction(()=>document.querySelector('#authError')?.textContent.includes('错误'));assert.equal(await page.locator('.app.app-ready').count(),0);return 'Rejected; app remains locked'});
 await step('真实云端登录与70人','使用隔离账号表单登录','遮罩消失、服务端返回数据、70人',async()=>{await login(page);await nav('people');assert.equal(await page.locator('[data-open-person]').count(),70);const d=await cloud('load');assert.equal(d.payload.people.length,70);await page.screenshot({path:'evidence/login-people.png'});return{people:d.payload.people.length,version:d.version}});
 await step('修改人物与刷新持久化','编辑21号备注及状态，保存后刷新','云端字段保存，刷新仍为同值',async()=>{await page.locator('.edit-person[data-id=FR0021]').click();await page.locator('#modalForm [name=notes]').fill('E2E persistence');for(const n of ['opened','joined','vip'])await page.locator('#modalForm [name='+n+']').selectOption('1');await modalSave();await stored(p=>p.people.find(x=>x.id==='FR0021')?.crm?.notes==='E2E persistence');await page.reload({waitUntil:'networkidle'});await page.locator('.app.app-ready').waitFor({state:'visible'});await nav('people');await page.locator('.edit-person[data-id=FR0021]').click();assert.equal(await page.locator('#modalForm [name=notes]').inputValue(),'E2E persistence');await page.locator('#cancelModal').click()});
 await step('分组与联系记录','新增小组，21号加入；添加联系记录','云端保存，发言次数不计联系记录',async()=>{await nav('groups');await page.locator('#addGroup').click();await page.locator('#modalForm [name=name]').fill('E2E group');await page.locator('#modalForm [name=members][value=FR0021]').check();await modalSave();await nav('records');await page.locator('#addRecord').click();await page.locator('#modalForm [name=personId]').selectOption('FR0021');await page.locator('#modalForm [name=type]').selectOption('联系记录');await page.locator('#modalForm [name=title]').fill('E2E contact');await page.locator('#modalForm [name=content]').fill('联系确认完成');await modalSave();await stored(p=>p.customGroups.some(x=>x.name==='E2E group')&&p.records.some(x=>x.title==='E2E contact'))});
 await step('人物编号插入','写作区输入21后按Enter','生成21号真实姓名标签',async()=>{await nav('novel');await date('2026-09-29');await page.locator('#dailyEditor').fill('21');await page.locator('#dailyEditor').press('Enter');assert.equal(await page.locator('#dailyEditor .person-token[data-person=FR0021]').count(),1);return await page.locator('#dailyEditor').innerText()});
 await step('每日独立保存与准确发言计数','29日写A保存两次，30日写B保存两次，再切回29日','云端发言数1→1→2→2；A/B独立',async()=>{await write('21：今天第一次参加大宗交易，对助理比较信任。');let p=await stored(p=>p.records.filter(r=>r.personId==='FR0021'&&r.type==='发言记录').length===1);await page.locator('#saveDaily').click();await new Promise(r=>setTimeout(r,1000));p=(await cloud('load')).payload;assert.equal(p.records.filter(r=>r.personId==='FR0021'&&r.type==='发言记录').length,1);await date('2026-09-30');await write('21：第二次发言');await stored(p=>p.records.filter(r=>r.personId==='FR0021'&&r.type==='发言记录').length===2);await page.locator('#saveDaily').click();await date('2026-09-29');assert.ok((await page.locator('#dailyEditor').innerText()).includes('今天第一次'));p=await stored(p=>p.dailyDocs['2026-09-30']?.content.includes('第二次'));assert.equal(p.records.filter(r=>r.personId==='FR0021'&&r.type==='发言记录').length,2);assert.equal(await page.locator('#speechRanking .speech-row').count(),70);assert.match(await page.locator('#speechRanking .speech-row').first().textContent(),/21.*2次/);return{dates:Object.keys(p.dailyDocs),speechCount:2}});
 await step('人物记忆与成长','点击21号排行，再打开人物详情','记忆和成长包含发言、联系记录',async()=>{await page.locator('[data-sp=FR0021]').click();assert.match(await page.locator('#memoryTimeline').textContent(),/今天第一次/);await nav('people');await page.locator('[data-open-person=FR0021]').click();const text=await page.locator('#personDetailContent').textContent();assert.match(text,/今天第一次/);assert.match(text,/E2E contact/)});
 await step('开户入群VIP与经历冲突','次日依次写否认状态和交易经历','每种否认出现对应提示',async()=>{await nav('novel');await date('2026-10-01');for(const [t,k] of [['我从来没有开过账户','开户'],['我从来没有加入过群','入群'],['我不是VIP','VIP'],...['从未参与大宗交易','从未参与过大宗交易','从来没有参与过大宗交易','从没参与过大宗交易','没有参与过大宗交易'].map(t=>[t,'经历'])]){await write('21：'+t);assert.ok((await page.locator('#logicWarnings').textContent()).includes(k),t)}await write('')});
 await step('股票计划推荐资金与邀请','21号USD20000、22号USD1；建立DDD计划并推荐10人，邀请21号','22号排除；未知资金待确认；待买数即时更新',async()=>{await nav('people');for(const [id,value] of [['FR0021','20000'],['FR0022','1']]){await page.locator('[data-trade-pref='+id+']').click();await page.locator('#modalForm [name=usd]').fill(value);if(id==='FR0021')await page.locator('#modalForm [name=required]').selectOption('1');await modalSave()}await nav('tradeRecommend');await page.locator('#newOffer').click();await page.locator('#modalForm [name=symbol]').fill('DDD');await modalSave();await page.locator('#recommendPeople').click();assert.equal(await page.locator('.candidate-card').count(),10);assert.equal(await page.locator('[data-invite=FR0022]').count(),0);assert.match(await page.locator('#tradeRecommendBody').textContent(),/待确认/);await page.locator('[data-invite=FR0021]').click();await nav('overview');assert.equal(await page.locator('[data-dash=buy] strong').textContent(),'1');await stored(p=>p.portfolio.buyPlans.some(x=>x.personId==='FR0021'&&x.status==='planned'))});
 await step('买入150股与独立批次','21号确认输入150；另一推荐人也买入150','两笔150股USD持仓、独立batchId；参与次数为1',async()=>{await nav('tradeRecommend');await page.locator('[data-confirm-buy=FR0021]').click();await page.locator('#modalForm [name=quantity]').fill('150');await modalSave();const invite=page.locator('[data-invite]').first();const pid=await invite.getAttribute('data-invite');await invite.click();await page.locator('[data-confirm-buy='+pid+']').click();await page.locator('#modalForm [name=quantity]').fill('150');await modalSave();const p=await stored(p=>p.portfolio.holdings.length===2);assert.equal(p.portfolio.holdings[0].quantity,150);assert.equal(p.portfolio.holdings[0].currency,'USD');assert.notEqual(p.portfolio.holdings[0].batchId,p.portfolio.holdings[1].batchId);await nav('people');await page.locator('[data-open-person=FR0021]').click();assert.equal(await page.locator('.detail-kpi').filter({hasText:'参与次数'}).locator('strong').textContent(),'1');return p.portfolio.holdings.map(h=>({id:h.id,batchId:h.batchId,quantity:h.quantity,currency:h.currency}))});
 await step('未到期禁售与持仓冲突','打开持仓，检查卖出禁用；写无持仓语句','显示数量价格期限；禁售；提示冲突',async()=>{await nav('holdingsV2');for(const b of await page.locator('[data-sell-batch]').all())assert.equal(await b.isDisabled(),true);const t=await page.locator('#holdingsV2Body').textContent();assert.match(t,/150/);assert.match(t,/65/);await nav('novel');await write('21：我现在没有任何股票持仓。');assert.match(await page.locator('#logicWarnings').textContent(),/持仓状态冲突/);await write('')});
 await step('到期卖出与利润','测试浏览器时钟前移3天1分钟；卖出21号持仓，价格80','已售；盈利USD2250，23.08%；云端保存',async()=>{await page.clock.setFixedTime(new Date(Date.now()+3*86400000+60000));await nav('holdingsV2');await page.locator('[data-sell-batch]').first().click();await page.locator('#modalForm [name=soldPrice]').fill('80');await modalSave();const p=await stored(p=>p.portfolio.holdings.some(x=>x.personId==='FR0021'&&x.status==='sold'));const h=p.portfolio.holdings.find(x=>x.personId==='FR0021');assert.equal((h.soldPrice-h.buyPrice)*h.quantity,2250);await nav('people');await page.locator('[data-open-person=FR0021]').click();const t=await page.locator('#personDetailContent').textContent();assert.match(t,/2,250/);assert.match(t,/23\.08%/);assert.match(t,/完成卖出/);await page.screenshot({path:'evidence/profit-growth.png'});return{quantity:h.quantity,buy:h.buyPrice,sell:h.soldPrice,profit:2250,rate:23.0769230769,clock:'browser advanced 3 days 1 minute'}});
 await step('四币种交易与收益隔离','为21号分别执行EUR/HKD/CNY小额买卖，与USD交易共存','云端保留四种币种，收益分别计算',async()=>{
  await nav('people');await page.locator('[data-trade-pref=FR0021]').click();for(const currency of ['eur','hkd','cny'])await page.locator('#modalForm [name='+currency+']').fill('20000');await modalSave();
  for(const code of ['EUR','HKD','CNY']){
   await nav('tradeRecommend');await page.locator('#newOffer').click();await page.locator('#modalForm [name=symbol]').fill('E2E'+code);await page.locator('#modalForm [name=currency]').selectOption(code);await page.locator('#modalForm [name=shares]').fill('1');await page.locator('#modalForm [name=price]').fill('10');await page.locator('#modalForm [name=days]').fill('0');await page.locator('#modalForm [name=count]').fill('1');await modalSave();await page.locator('#recommendPeople').click();await page.locator('[data-invite=FR0021]').click();await page.locator('[data-confirm-buy=FR0021]').click();await page.locator('#modalForm [name=quantity]').fill('2');await modalSave();await nav('holdingsV2');await page.locator('.batch-card').filter({hasText:'E2E'+code}).locator('[data-sell-batch]').click();await page.locator('#modalForm [name=soldPrice]').fill('12');await modalSave();
  }
  const p=await stored(p=>p.portfolio.holdings.filter(h=>h.personId==='FR0021'&&h.status==='sold').length===4);const sold=p.portfolio.holdings.filter(h=>h.personId==='FR0021'&&h.status==='sold');assert.deepEqual(sold.map(h=>h.currency).sort(),['CNY','EUR','HKD','USD']);for(const h of sold.filter(h=>h.currency!=='USD'))assert.equal((h.soldPrice-h.buyPrice)*h.quantity,4);await nav('people');await page.locator('[data-open-person=FR0021]').click();const text=await page.locator('#personDetailContent').textContent();for(const code of ['USD','EUR','HKD','CNY'])assert.ok(text.includes(code));return sold.map(h=>({currency:h.currency,profit:(h.soldPrice-h.buyPrice)*h.quantity}));
 });
 await step('DOCX导出','打开文档并导出','下载有效ZIP格式DOCX',async()=>{await nav('novel');await date('2026-09-29');const download=page.waitForEvent('download');await page.locator('#docxExport').click();const file=await download;await file.saveAs('evidence/daily.docx');assert.equal(fs.readFileSync('evidence/daily.docx').subarray(0,2).toString(),'PK')});
 await step('刷新与新浏览器会话持久化','刷新后检查；全新context重新登录','修改人物、日期文档、已售状态仍存在',async()=>{await page.reload({waitUntil:'networkidle'});await page.locator('.app.app-ready').waitFor({state:'visible'});const context=await browser.newContext();const fresh=await context.newPage();await login(fresh);await fresh.locator('.nav [data-page=novel]').click();await fresh.locator('#dailyDatePicker').fill('2026-09-29');await fresh.locator('#openDate').click();assert.match(await fresh.locator('#dailyEditor').innerText(),/今天第一次/);const p=(await cloud('load')).payload;assert.equal(p.people.find(x=>x.id==='FR0021')?.crm?.notes,'E2E persistence');assert.equal(p.portfolio.holdings.find(x=>x.personId==='FR0021').status,'sold');await context.close()});
 await step('桌面导航与390px手机','8个导航，收起/展开测宽，手机每页检查溢出','展开210–230，收起72–76，手机≤80且无溢出',async()=>{const width=()=>page.locator('.sidebar').evaluate(e=>e.getBoundingClientRect().width);const expanded=await width();assert.ok(expanded>=210&&expanded<=230,String(expanded));await page.locator('.nav-collapse').click();await page.waitForTimeout(400);const collapsed=await width();assert.ok(collapsed>=72&&collapsed<=76,String(collapsed));await page.setViewportSize({width:390,height:844});const dims=[];for(const id of ['overview','people','groups','records','novel','topics','tradeRecommend','holdingsV2']){await nav(id);const d=await page.evaluate(()=>({viewport:innerWidth,scroll:document.documentElement.scrollWidth,sidebar:document.querySelector('.sidebar').getBoundingClientRect().width}));assert.ok(d.scroll<=390&&d.sidebar<=80,JSON.stringify({id,...d}));dims.push({id,...d})}await page.screenshot({path:'evidence/mobile.png'});return{expanded,collapsed,dims}});
 await step('退出会话撤销','点击退出，再用该session调用load','退出返回登录页，旧session HTTP401',async()=>{const response=page.waitForResponse(r=>r.url()===endpoint&&r.request().postDataJSON()?.action==='logout');await page.locator('#logoutBtn').click();assert.equal((await(await response).json()).ok,true);await page.locator('#loginForm').waitFor();/* verify the revoked token belongs to this page via logout request */const raw=(await response).request().headers().authorization;const r=await fetch(endpoint,{method:'POST',headers:{apikey:key,'Content-Type':'application/json',Authorization:raw},body:JSON.stringify({action:'load'})});assert.equal(r.status,401);return{status:r.status}});
 await step('客户端无明文密码缓存','检查浏览器localStorage/sessionStorage内容','均不包含本次密码',async()=>{const matches=await page.evaluate(password=>[localStorage,sessionStorage].some(storage=>Object.values(storage).some(v=>v.includes(password))),creds.password);assert.equal(matches,false)});
 await step('登录初始化独立于业务错误','新页面阻断workspace-core.js加载','登录表单仍显示，后台仍锁定',async()=>{const context=await browser.newContext();const p=await context.newPage();await p.route('**/workspace-core.js*',r=>r.abort());await p.goto(URL);await p.locator('#loginForm').waitFor({state:'visible'});assert.equal(await p.locator('.app').isVisible(),false);await context.close();return 'Fault injection: core blocked; auth visible'});
 await step('运行时错误','收集全流程console与pageerror','无意外错误',()=>{assert.deepEqual(errors,[]);return{errors}});
})().catch(async e=>{console.error(e.message);if(page)await page.screenshot({path:'evidence/failure.png'}).catch(()=>{});process.exitCode=1}).finally(async()=>{fs.writeFileSync('evidence/results.json',JSON.stringify({url:URL,results,errors,responses},null,2));if(browser)await browser.close()});
