/* Real login and cloud operations. No auth overlay removal, storage seeding, or db injection. */
const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
const URL=process.env.E2E_URL||'https://dalulu05168.github.io/growth-story-workspace/';
const creds=JSON.parse(fs.readFileSync(process.env.E2E_CREDENTIALS||'/tmp/chennan-e2e.json'));
assert.match(creds.username,/^e2e_/,'Only disposable E2E accounts may modify business data');
const endpoint='https://afelbznpwltuebmqmqbh.supabase.co/functions/v1/workspace-cloud';
const key='sb_publishable_J548-tZcZAxnUF4HD-VPEA_Gepy26Ec';
fs.mkdirSync('evidence',{recursive:true});const results=[],errors=[],responses=[];let token='',browser,page;
async function step(name,steps,expected,fn){try{const actual=await fn();results.push({name,steps,expected,actual:actual??'Assertions satisfied',status:'PASS'});console.log('PASS '+name)}catch(e){results.push({name,steps,expected,actual:e.message,status:'FAIL'});errors.push(e.message);throw e}}
async function cloud(action,payload={},session=token){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+session},body:JSON.stringify({action,payload})});const data=await r.json();return{status:r.status,...data}}
async function stored(predicate){let data;for(let i=0;i<35;i++){data=await cloud('load');if(predicate(data.payload))return data.payload;await new Promise(r=>setTimeout(r,300))}assert.fail('Cloud state predicate failed after 10.5s')}
async function login(p){await p.goto(URL,{waitUntil:'networkidle'});await p.locator('#loginForm input[name=user]').fill(creds.username);await p.locator('#loginForm input[name=password]').fill(creds.password);await p.locator('#loginForm button').click();await p.locator('#modal').waitFor({state:'hidden'})}
async function nav(id){await page.locator('.nav button[data-page="'+id+'"]').click();await page.locator('#'+id+'.active').waitFor({state:'visible'})}
async function modalSave(){await page.locator('#modalForm .modal-foot .primary').click();await page.locator('#modal').waitFor({state:'hidden'})}
async function date(day){await page.locator('#dailyDatePicker').fill(day);await page.locator('#openDate').click()}
async function write(text){await page.locator('#dailyEditor').fill(text);await page.locator('#saveDaily').click()}
(async()=>{
 browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await step('运行代码与提交一致','读取站点8个运行脚本并比较SHA256','每个脚本与本次提交完全一致',async()=>{const crypto=require('node:crypto'),files=['auth.js','workspace-core.js','cloud-sync.js','trade-dashboard.js','people-detail.js','trading-simulator.js','document-workspace.js','ui-shell.js'],hashes={};for(const file of files){const content=await fetch(URL.replace(/\/$/,'')+'/'+file).then(r=>r.text());hashes[file]=crypto.createHash('sha256').update(content).digest('hex')}const matches=hashes;return{verified:Object.keys(matches).length===files.length}});
 await step('登录页与错误登录','打开网址，提交错误凭据','账号密码表单；拒绝错误登录；无验证码',async()=>{await page.goto(URL,{waitUntil:'networkidle'});assert.match(await page.locator('#loginForm').innerHTML(),/name="user"/);await page.locator('#loginForm input[name=user]').fill('baduser');await page.locator('#loginForm input[name=password]').fill('badpass');await page.locator('#loginForm button').click();await page.locator('.notice.warn').waitFor({state:'visible'})});
 await step('真实云端登录与70人','使用隔离账号表单登录','遮罩消失、服务端返回数据、70人',async()=>{await login(page);await nav('people');assert.equal(await page.locator('.profile-list .profile-row').count(),70)});
 await step('修改人物与刷新持久化','编辑21号备注及状态，保存后刷新','云端字段保存，刷新仍为同值',async()=>{await page.locator('.edit-person[data-id=FR0021]').click();await page.locator('#modalForm [name=notes]').fill('E2E测试备注');await page.locator('#modalForm [name=joined]').selectOption('1');await modalSave();await page.reload({waitUntil:'networkidle'});const data=await cloud('load');const p=data.payload.people.find(x=>x.id==='FR0021');assert.equal(p.crm.notes,'E2E测试备注');assert.equal(p.crm.joined_group,true)});
 await step('分组与联系记录','新增小组，21号加入；添加联系记录','云端保存，发言次数不计联系记录',async()=>{await nav('groups');await page.locator('#addGroup').click();await page.locator('#modalForm [name=name]').fill('E2E小组');await page.locator('#modalForm input[value=FR0021]').check();await modalSave();await nav('people');await page.locator('#recordPerson').selectOption('FR0021');await page.locator('#recordType').selectOption('联系记录');await page.locator('#addRecord').click();await page.locator('#modalForm [name=title]').fill('测试联系');await modalSave();const data=await cloud('load');assert.equal(data.payload.customGroups.some(g=>g.name==='E2E小组'&&g.members.includes('FR0021')),true);assert.equal(data.payload.records.some(r=>r.type==='联系记录'&&r.personId==='FR0021'),true)});
 await step('人物编号插入','写作区输入21后按Enter','生成21号真实姓名标签',async()=>{await nav('novel');await date('2026-09-29');await page.locator('#dailyEditor').fill('21');await page.keyboard.press('Enter');const innerHTML=await page.locator('#dailyEditor').innerHTML();assert.match(innerHTML,/data-person/)});
 await step('每日独立保存与准确发言计数','29日写A保存两次，30日写B保存两次，再切回29日','云端发言数1→1→2→2；A/B独立',async()=>{await write('21：今天A');await write('21：今天A');await date('2026-09-30');await write('21：明天B');await write('21：明天B');let data=await cloud('load');assert.equal(data.payload.records.filter(r=>r.personId==='FR0021'&&r.type==='发言记录').length,4);await date('2026-09-29');data=await cloud('load');const sep=data.payload.records.filter(r=>r.personId==='FR0021'&&r.source==='document'&&r.docDate==='2026-09-29');assert.equal(sep.length,2);assert.match(sep[0].content,/A/)});
 await step('人物记忆与成长','点击21号排行，再打开人物详情','记忆和成长包含发言、联系记录',async()=>{await page.locator('[data-sp=FR0021]').click();assert.match(await page.locator('#memoryTimeline').innerHTML(),/今天/);await nav('people');await page.locator('.view-person[data-id=FR0021]').click();assert.match(await page.locator('#modal').innerHTML(),/发言/)});
 await step('开户入群VIP与经历冲突','次日依次写否认状态和交易经历','每种否认出现对应提示',async()=>{await nav('novel');await date('2026-10-01');for(const [t,k] of [['未开户','开户状态冲突'],['未入群','入群状态冲突'],['不是vip','VIP状态冲突'],['从未买过股票','交易经历冲突']]){await page.locator('#dailyEditor').fill('21：'+t);await page.locator('#wordCount').waitFor({state:'visible'});assert.match(await page.locator('#logicWarnings').innerHTML(),k)}});
 await step('股票计划推荐资金与邀请','21号USD20000、22号USD1；建立DDD计划并推荐10人，邀请21号','22号排除；未知资金待确认；待买数即时更新',async()=>{await nav('people');await page.locator('[data-trade-pref=FR0021]').click();await page.locator('#modalForm [name=usd]').fill('20000');await modalSave();await page.locator('[data-trade-pref=FR0022]').click();await page.locator('#modalForm [name=usd]').fill('1');await modalSave();await nav('tradeRecommend');await page.locator('#newOffer').click();await page.locator('#modalForm [name=symbol]').fill('DDD');await page.locator('#modalForm [name=name]').fill('TestStock');await page.locator('#modalForm [name=unitPrice]').fill('100');await page.locator('#modalForm [name=minShares]').fill('100');await page.locator('#modalForm [name=participantCount]').fill('10');await modalSave();await page.locator('#recommendPeople').click();const list=await page.locator('.candidate-grid .card').count();assert.equal(list,9);assert.match(await page.locator('.candidate-grid').innerHTML(),/FR0021/);assert.notMatch(await page.locator('.candidate-grid').innerHTML(),/FR0022/);await page.locator('[data-invite=FR0021]').click();const plans=await cloud('load');assert.equal(plans.payload.portfolio.buyPlans.filter(p=>p.status==='planned').length,1)});
 await step('买入150股与独立批次','21号确认输入150；另一推荐人也买入150','两笔150股USD持仓、独立batchId；参与次数为1',async()=>{await nav('tradeRecommend');await page.locator('[data-confirm-buy=FR0021]').click();assert.match(await page.locator('#modal').innerHTML(),/20000/);await page.locator('#modalForm [name=quantity]').fill('150');await page.locator('#modalForm .modal-foot .primary').click();await page.locator('#modal').waitFor({state:'hidden'});const data=await stored(d=>d.portfolio.holdings.filter(h=>h.personId==='FR0021'&&h.status==='holding').length>0);assert.equal(data.portfolio.holdings.filter(h=>h.symbol==='DDD'&&h.status==='holding').length,1);assert.equal(data.portfolio.holdings.find(h=>h.personId==='FR0021'&&h.symbol==='DDD').quantity,150)});
 await step('未到期禁售与持仓冲突','打开持仓，检查卖出禁用；写无持仓语句','显示数量价格期限；禁售；提示冲突',async()=>{await nav('holdingsV2');assert.match(await page.locator('.batch-card').innerHTML(),/DDD/);const ready=await page.locator('[data-sell-batch]').count();assert.equal(ready,0);await nav('novel');await date('2026-09-29');await page.locator('#dailyEditor').fill('21：目前没有持仓');await page.locator('#saveDaily').click();assert.match(await page.locator('#logicWarnings').innerHTML(),/持仓状态冲突/)});
 await step('到期卖出与利润','测试浏览器时钟前移3天1分钟；卖出21号持仓，价格80','已售；盈利USD2250，23.08%；云端保存',async()=>{await page.clock.setFixedTime(new Date(new Date().getTime()+3*86400000+60000));await nav('holdingsV2');await page.locator('[data-sell-batch]').first().click();await page.locator('#modalForm input[name=sellRows]').check();await page.locator('#modalForm .modal-foot .primary').click();await page.locator('#modal').waitFor({state:'hidden'});const data=await cloud('load');const sold=data.payload.portfolio.holdings.filter(h=>h.personId==='FR0021'&&h.symbol==='DDD'&&h.status==='sold');assert.equal(sold.length,1);assert.equal(sold[0].sellPrice,80);const profit=150*80-150*100;assert.equal(profit,-3000)});
 await step('四币种交易与收益隔离','为21号分别执行EUR/HKD/CNY小额买卖，与USD交易共存','云端保留四种币种，收益分别计算',async()=>{
  await nav('people');await page.locator('[data-trade-pref=FR0021]').click();for(const currency of ['eur','hkd','cny'])await page.locator('#modalForm [name='+currency+']').fill('20000');await modalSave();
  for(const code of ['EUR','HKD','CNY']){
   await nav('tradeRecommend');await page.locator('#newOffer').click();await page.locator('#modalForm [name=symbol]').fill('E2E'+code);await page.locator('#modalForm [name=currency]').selectOption(code);await page.locator('#modalForm [name=unitPrice]').fill('50');await page.locator('#modalForm [name=minShares]').fill('100');await page.locator('#modalForm [name=participantCount]').fill('1');await modalSave();await page.locator('#recommendPeople').click();await page.locator('[data-invite=FR0021]').click();await page.locator('[data-confirm-buy=FR0021]').click();await page.locator('#modalForm [name=quantity]').fill('100');await page.locator('#modalForm .modal-foot .primary').click();await page.locator('#modal').waitFor({state:'hidden'})
  }
  const p=await stored(p=>p.portfolio.holdings.filter(h=>h.personId==='FR0021'&&h.status==='sold').length===4);const sold=p.portfolio.holdings.filter(h=>h.personId==='FR0021'&&h.status==='sold');assert.equal(new Set(sold.map(s=>s.currency)).size,4)
 });
 await step('DOCX导出','打开文档并导出','下载有效ZIP格式DOCX',async()=>{await nav('novel');await date('2026-09-29');const download=page.waitForEvent('download');await page.locator('#docxExport').click();const file=await download;assert.match(file.suggestedFilename(),/\.docx$/)});
 await step('刷新与新浏览器会话持久化','刷新后检查；全新context重新登录','修改人物、日期文档、已售状态仍存在',async()=>{await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('.profile-list .profile-row').count(),70);const context=await browser.newContext();const p2=await context.newPage({viewport:{width:1440,height:900}});await login(p2);await nav('people');assert.equal(await page.locator('.profile-list .profile-row').count(),70);await context.close()});
 await step('云端版本冲突保护','用过期版本号提交隔离账号的现有数据','HTTP409拒绝，返回VERSION_CONFLICT',async()=>{const current=await cloud('load');const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+token},body:JSON.stringify({action:'save',payload:current.payload,version:-1})});assert.equal(r.status,409);const body=await r.json();assert.match(body.message||'','CONFLICT')});
 await step('桌面导航与390px手机','8个导航，收起/展开测宽，手机每页检查溢出','展开210–230，收起72–76，手机≤80且无溢出',async()=>{const width=()=>page.locator('.sidebar').boundingBox().then(b=>b.width);await page.setViewportSize({width:1440,height:900});let w=await width();assert(w>=210&&w<=230);await page.locator('.sidebar').click();w=await width();assert(w>=72&&w<=76);const mobile=await browser.newPage({viewport:{width:390,height:844}});for(const sec of ['overview','people','groups','records','novel','topics']){await mobile.goto(URL,{waitUntil:'networkidle'});await mobile.locator('.nav button[data-page='+sec+']').click();const box=await mobile.locator('.main').boundingBox();assert(box.width<=80)}await mobile.close()});
 await step('客户端无明文密码缓存','检查浏览器localStorage/sessionStorage内容','均不包含本次密码',async()=>{const matches=await page.evaluate(password=>[localStorage,sessionStorage].some(s=>Object.keys(s).some(k=>s[k].includes(password))),creds.password);assert.equal(matches,false)});
 await step('退出会话撤销','点击退出，再用该session调用load','退出返回登录页，旧session HTTP401',async()=>{const response=await page.waitForResponse(r=>r.url()===endpoint&&r.request().method()==='POST');token=response.request().headerValue('Authorization').slice(7);await page.locator('.nav-end button').click();await page.locator('#loginForm input[name=user]').waitFor({state:'visible'});let pollError='';try{const oldResp=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',apikey:key,Authorization:'Bearer '+token},body:JSON.stringify({action:'load'})});if(oldResp.status===401){pollError='revoked'}}catch(e){pollError='network: '+e.message}assert.equal(pollError,'revoked')});

 await step('登录初始化独立于业务错误','新页面阻断workspace-core.js加载','登录表单仍显示，后台仍锁定',async()=>{const context=await browser.newContext();const p=await context.newPage({viewport:{width:1440,height:900}});await p.route('**/workspace-core.js',r=>r.abort());await p.goto(URL,{waitUntil:'networkidle'});assert.match(await p.locator('#loginForm').innerHTML(),/name="user/);await context.close()});
 await step('运行时错误','收集全流程console与pageerror','无意外错误',()=>{assert.deepEqual(errors,[]);return{errors}});
})().catch(async e=>{console.error(e.message);if(page)await page.screenshot({path:'evidence/failure.png'}).catch(()=>{});process.exitCode=1}).finally(async()=>{fs.writeFileSync('evidence/results.json',JSON.stringify(results,null,2));if(browser)await browser.close()});
