/* Real-account desktop recovery acceptance. Disposable e2e accounts only. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),{contrastAudit}=require('./contrast-audit.cjs');
const creds=JSON.parse(fs.readFileSync(process.env.E2E_CREDENTIALS));assert.match(creds.username,/^e2e_/);
(async()=>{const browser=await chromium.launch();try{const context=await browser.newContext({viewport:{width:1920,height:1080},reducedMotion:'reduce'}),page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(process.env.E2E_URL);await page.locator('#loginUser').fill(creds.username);await page.locator('#loginPassword').fill(creds.password);await page.locator('#loginForm [type=submit]').click();await page.locator('.app.app-ready').waitFor({state:'visible'});
 await page.locator('[data-page=novel]').click();await page.locator('#dailyEditor').fill('desktop recovery first version');await page.evaluate(()=>ChenNanCloud.flush(true));await page.locator('#writingHistory').click();await page.locator('#checkpointNow').click();await page.locator('#desktopDialog [data-close]').click();await page.locator('#dailyEditor').fill('desktop recovery second version');await page.locator('#writingHistory').click();await page.locator('[data-version]').filter({hasText:'手动保留'}).first().click();await contrastAudit(page,'#desktopDialog');await page.locator('#restoreDocument').click();assert.equal(await page.locator('#dailyEditor').innerText(),'desktop recovery first version');await page.evaluate(()=>ChenNanCloud.flush(true));await page.reload();await page.locator('.app.app-ready').waitFor({state:'visible'});console.log('PASS history cloud persistence');await page.locator('[data-page=novel]').click();assert.equal(await page.locator('#dailyEditor').innerText(),'desktop recovery first version');assert(await page.evaluate(()=>Object.values(db.documentHistory).flat().some(x=>x.document.content==='desktop recovery second version')));
 await page.locator('[data-sp]').first().click();await page.locator('#memoryRelations').fill('C.02 是姐姐');await page.locator('#memoryForeshadowing').fill('下一章回应购房承诺');await page.evaluate(()=>ChenNanCloud.flush(true));await contrastAudit(page);await page.locator('#writingFocus').click();assert.equal(await page.locator('.memory-panel').isVisible(),false);await page.locator('#writingFocus').click();const grip=page.locator('.writing-resizer.left');const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('chennan-writing-widths')||'{}').left||150);await grip.focus();await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('chennan-writing-widths')).left),before+10);
 await page.keyboard.press('Control+k');await page.locator('#workspaceQuery').fill('desktop recovery first');await page.locator('[data-result]').filter({hasText:'文档'}).click();assert.equal(await page.locator('#dailyEditor').innerText(),'desktop recovery first version');
 const resize=await page.locator('.writing-resizer.left').boundingBox();await page.mouse.move(resize.x+resize.width/2,resize.y+30);await page.mouse.down();await page.mouse.move(resize.x+resize.width/2+20,resize.y+30);await page.mouse.up();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('chennan-writing-widths')).left),before+30);console.log('PASS memory, focus, resize and search');await page.locator('#workspaceBackup').click();await page.locator('[data-download]').first().waitFor();const count=await page.locator('[data-download]').count();await page.locator('#createBackup').click();await page.waitForFunction(n=>document.querySelectorAll('[data-download]').length===Math.min(30,n+1),count);await contrastAudit(page,'#desktopDialog');const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#exportWorkspace').click()]);const downloadPath=await download.path();const exported=JSON.parse(fs.readFileSync(downloadPath));assert.equal(exported.format,'chennan-workspace-backup');assert.equal(exported.payload.people.length,70);assert(!JSON.stringify(exported).includes(creds.password));await page.locator('#desktopDialog [data-close]').click();await page.locator('#dailyEditor').fill('desktop recovery third version');await page.evaluate(()=>ChenNanCloud.flush(true));await page.locator('#workspaceBackup').click();await page.locator('[data-restore]').first().click();await page.waitForFunction(()=>!document.getElementById('desktopDialog').open);assert.equal(await page.locator('#dailyEditor').innerText(),'desktop recovery first version');await page.evaluate(()=>ChenNanCloud.flush(true));
 await page.locator('#workspaceBackup').click();await page.locator('#importWorkspace').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({people:[]}))});await page.locator('#desktopDialog [role=alert]').getByText(/备份格式不完整/).waitFor();await page.locator('#importWorkspace').setInputFiles(downloadPath);await page.waitForFunction(()=>!document.getElementById('desktopDialog').open);assert.equal(await page.locator('#dailyEditor').innerText(),'desktop recovery first version');console.log('PASS cloud snapshot recovery and validated file import');
 // Session tokens stay private. Revoking other sessions must keep this session alive.
 const other=await browser.newContext({reducedMotion:'reduce'}),p2=await other.newPage();await p2.goto(process.env.E2E_URL);await p2.locator('#loginUser').fill(creds.username);await p2.locator('#loginPassword').fill(creds.password);await p2.locator('#loginForm [type=submit]').click();await p2.locator('.app.app-ready').waitFor({state:'visible'});await page.locator('#accountSecurity').click();await page.locator('[data-revoke]').first().waitFor();await page.locator('#revokeOtherSessions').click();await page.waitForFunction(()=>!document.querySelector('[data-revoke]'));assert.equal(await page.evaluate(async()=>{await ChenNanCloud.listSessions();return true}),true);assert.equal(await p2.evaluate(async()=>{try{await ChenNanCloud.listSessions();return false}catch(e){return e.status===401}}),true);await other.close();assert.deepEqual(errors,[]);console.log('PASS desktop history rollback, persisted memory notes, focus, resize, search, export/restore and session revocation');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
