const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const E=require('../script-engine.js'),full=JSON.parse(fs.readFileSync('data/72人物整合汇总.json')),people=JSON.parse(fs.readFileSync('data/people.json')).people;
const reg=E.registry(full,people),blank=()=>E.migrate(null,reg),sc=(time='09:30')=>E.scene({date:'2026-10-06',time,sourceKind:'assistant',sourceText:'用户提供的原话',offerId:'o1'});
function message(id='01',text='请核对这项指标的数据口径。',time='09:30'){return {message_id:'m1',character_id:id,member_type:E.memberType(reg.byId[id]),suggested_time:time,message_type:'question',reply_to:'source',text,attachment_status:'none',trade_fact_ids:[]};}
function simulator(){const db={people:[{id:'FR0001',account:{opened:true}}],records:[],customGroups:[],tradeSim:{offers:[{id:'o1',symbol:'TEST',minShares:10,unitPrice:20,holdDays:0,participantCount:1}],recommendations:[]},portfolio:{holdings:[],buyPlans:[]}};
const ctx={db,window:{},crypto:require('crypto').webcrypto,save(){},toast(){},person:id=>db.people.find(p=>p.id===id),pEnthusiasm:()=>0};vm.createContext(ctx);vm.runInContext(fs.readFileSync('trading-simulator.js','utf8').replace('setupUI();bindNav();','renderRecommend=()=>{};globalThis.api={makeRecommendations,setCandidate,executeBuy};'),ctx);ctx.api.makeRecommendations('o1');return {db,api:ctx.api,snapshot:()=>JSON.parse(JSON.stringify(ctx.window.ChenNanTrading.scriptSnapshot({date:db.tradeSim.recommendations[0].date,offerId:'o1',toId:reg.toId})))};}
test('formal 72 profiles preserved byte for byte in workspace adapter',()=>{assert.equal(full.profiles.length,72);for(const p of full.profiles.filter(p=>/^\d{2}$/.test(p.character_id)))assert.deepEqual(people.find(x=>x.character_id===p.character_id).source_profile,p);assert.equal(reg.toId('FR0001'),'01');assert.equal(reg.toId('Elena'),null);assert.equal(fs.existsSync('data/france70-v6.1.json'),false);});
test('course boundaries and evening override',()=>{for(const [time,period] of [['09:00','morning'],['11:59','morning'],['12:00','rest'],['13:00','afternoon'],['16:59','afternoon'],['17:00','rest'],['18:30','rest'],['19:00','evening'],['20:59','evening'],['21:00','rest']])assert.equal(E.stageAt(time).period,period);assert.throws(()=>sc('18:00'),/休息/);});
test('morning scheduling exceeds four, includes old/new, cooldown and direct exemption',()=>{const state=blank(),selected=E.select(reg,state,sc(),{required_participants:[]});assert.ok(selected.length>4);assert.equal(new Set(selected.map(id=>reg.byId[id].member_type)).size,2);state.sessions=[{messages:Array.from({length:3},()=>({character_id:'01'}))}];assert.ok(!E.select(reg,state,sc(),{}).includes('01'));assert.ok(E.select(reg,state,sc(),{},{directTargets:['01']}).includes('01'));});
test('actual simulator state read without mutation, invitation never equals reservation or fill',()=>{const f=simulator(),before=JSON.stringify(f.db);let sim=f.snapshot();assert.equal(JSON.stringify(f.db),before);assert.equal(sim.reservation_state,'not_required');assert.equal(sim.facts[0].kind,'pending');assert.equal(f.api.executeBuy('o1','FR0001',10),false);f.api.setCandidate('o1','FR0001','invited');sim=f.snapshot();assert.equal(sim.facts[0].kind,'invited');assert.equal(f.api.executeBuy('o1','FR0001',10),true);sim=f.snapshot();assert.ok(sim.facts.some(f=>f.kind==='bought'));assert.deepEqual(sim.current_holders,['01']);});
test('buy and sell statements must match actual simulator records',()=>{const f=simulator();f.api.setCandidate('o1','FR0001','invited');let sim=f.snapshot(),scene=sc('15:00'),m=message('01','我已经买入。','15:00');m.trade_fact_ids=[sim.facts[0].id];assert.ok(E.validate({messages:[m]},reg,blank(),scene,sim,['01']).errors.length);f.api.executeBuy('o1','FR0001',10);sim=f.snapshot();assert.equal(E.validate({messages:[m]},reg,blank(),scene,sim,['01']).errors.length,0);m.text='我已经卖出。';assert.ok(E.validate({messages:[m]},reg,blank(),scene,sim,['01']).errors.length);f.db.portfolio.holdings[0].status='sold';f.db.portfolio.holdings[0].soldAt=scene.date+'T14:01:00Z';sim=f.snapshot();m.trade_fact_ids=[sim.facts.find(f=>f.kind==='sold').id];m.suggested_time='14:00';assert.equal(E.validate({messages:[m]},reg,blank(),sc('14:00'),sim,['01']).errors.length,0);});
test('ten trade participants bypass ordinary course count',()=>{const selected=E.select(reg,blank(),sc('15:00'),{required_participants:Array.from({length:10},(_,i)=>String(i+1).padStart(2,'0'))});assert.ok(selected.length>=10);for(let i=1;i<=10;i++)assert.ok(selected.includes(String(i).padStart(2,'0')));});
test('draft never changes memory; adoption preserves raw host and carries question into evening and next day',()=>{const state=blank(),before=JSON.stringify(state),m=message(),obj={messages:[m],memory_events:[{character_id:'01',event_type:'question',topic:'数据',summary_zh:m.text,source_message_id:'m1',evidence:m.text}]};const report=E.validate(obj,reg,state,sc(),{},['01']);assert.equal(report.errors.length,0);assert.equal(JSON.stringify(state),before);assert.throws(()=>E.adopt(state,report,sc(),{expectedRevision:0,sessionId:'s1'}),/尚未/);const next=E.adopt(state,report,sc(),{confirmed:true,expectedRevision:0,sessionId:'s1',simulation:{}});assert.equal(next.sessions[0].messages[0].text,sc().sourceText);assert.equal(next.sessions[0].messages[1].reply_to,'s1_source');assert.equal(next.questions.length,1);for(const scene of [sc('20:30'),{...sc(),date:'2026-10-07'}]){const p=E.prompt(reg,next,scene,{},['01']);assert.equal(p.open_questions.length,1);assert.equal(p.recent_sessions[0].id,'s1');}assert.throws(()=>E.adopt(next,report,sc(),{confirmed:true,expectedRevision:0,sessionId:'s2'}),/版本/);});
test('forged memory evidence, wrong member, fake image, bad replies rejected',()=>{for(const patch of [{character_id:'assistant'},{member_type:'new'},{attachment_status:'provided'},{reply_to:'missing'}])assert.ok(E.validate({messages:[{...message(),...patch}]},reg,blank(),sc(),{},['01']).errors.length);const m=message();assert.ok(E.validate({messages:[m],memory_events:[{character_id:'01',event_type:'opinion',source_message_id:'m1',evidence:'捏造的盈利',summary_zh:'赚了很多'}]},reg,blank(),sc(),{},['01']).errors.length);});
test('all records beyond forty retained and name changes preserve identity and memory',()=>{const state=blank(),messages=Array.from({length:51},(_,i)=>({...message('01','不同内容'+i),message_id:'m'+i})),report=E.validate({messages},reg,state,sc(),{},['01']);assert.equal(report.errors.length,0);const next=E.adopt(state,report,sc(),{confirmed:true,expectedRevision:0,sessionId:'s1',simulation:{}});assert.equal(next.sessions[0].messages.length,52);const renamed=JSON.parse(JSON.stringify(full));renamed.profiles[0].name='新姓名';const r=E.registry(renamed,people);assert.equal(r.toId('FR0001'),'01');assert.equal(E.prompt(r,next,sc(),{},['01']).selected_characters[0].name,'新姓名');assert.equal(next.sessions[0].messages[1].character_id,'01');});
test('closed session allows raw host archive but suppresses member generation',()=>{const scene={...sc('11:40'),closed:true},state=blank();assert.deepEqual(E.select(reg,state,scene,{}),[]);const report=E.validate({messages:[]},reg,state,scene,{},[]);const next=E.adopt(state,report,scene,{confirmed:true,expectedRevision:0,sessionId:'close',simulation:{}});assert.deepEqual(E.select(reg,next,sc(),{}),[]);assert.ok(E.select(reg,next,sc('13:00'),{}).length);});

// Regression: director's 19:30 lesson start and the latest five formal sessions.
test('Romanian professor lesson begins at 19:30, not 20:00',()=>{
 assert.equal(E.stageAt('19:14').stage,'opening');
 assert.equal(E.stageAt('19:15').stage,'review');
 assert.equal(E.stageAt('19:29').stage,'review');
 assert.equal(E.stageAt('19:30').stage,'lecture');
 assert.equal(E.stageAt('20:00').stage,'lecture');
 assert.equal(E.stageAt('20:30').stage,'discussion');
});
test('prompt includes the latest five formally saved sessions, not the oldest',()=>{
 const state=blank();
 state.sessions=Array.from({length:8},(_,i)=>({id:'s'+(7-i),createdAt:'2026-10-09T'+String(9+7-i).padStart(2,'0')+':00:00',messages:[{message_id:'archived_'+(7-i),character_id:'01',text:'历史原文'+(7-i)}]}));
 const p=E.prompt(reg,state,sc(),{},['01']);
 assert.deepEqual(p.recent_sessions.map(s=>s.id),['s7','s6','s5','s4','s3']);
 const participation=E.select(reg,state,sc(),{},{directTargets:['02']});
 assert.ok(participation.includes('02'),'direct selection remains functional');
});

test('freshness of recent memories is independent of imported session storage order',()=>{
 const state=blank();
 state.sessions=[{id:'old',createdAt:'2026-10-06T09:30:00',messages:[message('01','旧记录')]},{id:'new',createdAt:'2026-10-09T19:30:00',messages:[message('02','最新记录')]}];
 const p=E.prompt(reg,state,sc(),{},['02']);
 assert.deepEqual(p.recent_sessions.map(s=>s.id),['new','old']);
});
