// Execute production functions in isolated fixtures; never bypass auth in browser tests.
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function trading(){const db={people:[{id:'p1',account:{opened:true},finance:{},trade_profile:{available_funds:{USD:20000}}}],records:[],tradeSim:{offers:[{id:'o1',symbol:'DDD',currency:'USD',minShares:100,unitPrice:65,holdDays:3,participantCount:1}],recommendations:[]},portfolio:{holdings:[],buyPlans:[]}};let modal;const ctx={db,crypto:require('crypto').webcrypto,save(){},toast(){},person:id=>db.people.find(p=>p.id===id),pEnthusiasm:()=>0,openModal:(title,html,submit)=>{modal={title,html,submit}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('trading-simulator.js','utf8').replace('setupUI();bindNav();','renderRecommend=()=>{};globalThis.api={makeRecommendations,setCandidate,confirmBuy,executeBuy,personBudget};'),ctx);ctx.api.makeRecommendations('o1');ctx.api.setCandidate('o1','p1','invited');return {db,api:ctx.api,modal:()=>modal}}
test('confirmation opens quantity dialog before any holding is created',()=>{const f=trading();f.api.confirmBuy('o1','p1');assert.equal(f.db.portfolio.holdings.length,0);assert.ok(f.modal()?.html.includes('quantity'))});
test('funding uses the currency entered in trade preferences',()=>{const f=trading();assert.equal(f.api.personBudget(f.db.people[0],'USD'),20000);assert.equal(f.api.personBudget(f.db.people[0],'HKD'),null)});
test('independent executions receive distinct batches and requested 150 shares',()=>{const f=trading();f.api.executeBuy('o1','p1',150);f.db.people.push({id:'p2',account:{opened:true}});f.db.tradeSim.recommendations[0].candidates.push({personId:'p2',status:'invited'});f.api.executeBuy('o1','p2',150);assert.equal(f.db.portfolio.holdings[0].quantity,150);assert.notEqual(f.db.portfolio.holdings[0].batchId,f.db.portfolio.holdings[1].batchId)});
function documents(){const db={people:[],records:[],portfolio:{holdings:[]}};const ctx={db,window:{},document:{addEventListener(){}},render(){}};vm.createContext(ctx);const src=fs.readFileSync('document-workspace.js','utf8').replace('setup();','globalThis.api={detect,speechCount};');vm.runInContext(src,ctx);return{db,api:ctx.api}}
for(const [text,kind] of [['我从来没有开过账户','开户'],['我从来没有加入过群','入群'],['我现在没有任何股票持仓','持仓']])test('recognizes denial: '+text,()=>{const f=documents(),p={id:'p1',account:{opened:true},crm:{joined_group:true}};f.db.portfolio.holdings.push({personId:'p1',status:'holding'});assert.ok(f.api.detect(p,text).some(x=>x.includes(kind)))});
test('repeated negative statement is not interpreted as positive trade history',()=>{const f=documents(),p={id:'p1'};f.db.records.push({personId:'p1',content:'从未参与过大宗交易'});assert.equal(f.api.detect(p,'我从没参与过大宗交易').filter(x=>x.includes('经历冲突')).length,0)});
