// Execute production functions in isolated fixtures; never bypass auth in browser tests.
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function trading(){const db={people:[{id:'p1',account:{opened:true},finance:{},trade_profile:{available_funds:{USD:20000}}}],records:[],tradeSim:{offers:[{id:'o1',symbol:'DDD',currency:'USD',minShares:100,unitPrice:65,holdDays:3,participantCount:1}],recommendations:[]},portfolio:{holdings:[],buyPlans:[]}};let modal;const ctx={pAvatar:()=>'<img alt="头像">',pCode:p=>p?.id||'',db,crypto:require('crypto').webcrypto,save(){},toast(){},person:id=>db.people.find(p=>p.id===id),pEnthusiasm:()=>0,openModal:(title,html,submit)=>{modal={title,html,submit}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('trading-simulator.js','utf8').replace('setupUI();bindNav();','renderRecommend=()=>{};globalThis.api={makeRecommendations,setCandidate,confirmBuy,executeBuy,personBudget};'),ctx);ctx.api.makeRecommendations('o1');ctx.api.setCandidate('o1','p1','invited');return {db,api:ctx.api,modal:()=>modal}}
test('confirmation opens quantity dialog before any holding is created',()=>{const f=trading();f.api.confirmBuy('o1','p1');assert.equal(f.db.portfolio.holdings.length,0);assert.ok(f.modal()?.html.includes('quantity'))});
test('funding uses the currency entered in trade preferences',()=>{const f=trading();assert.equal(f.api.personBudget(f.db.people[0],'USD'),20000);assert.equal(f.api.personBudget(f.db.people[0],'HKD'),null)});
test('independent executions receive distinct batches and requested 150 shares',()=>{const f=trading();f.api.executeBuy('o1','p1',150);f.db.people.push({id:'p2',account:{opened:true}});f.db.tradeSim.recommendations[0].candidates.push({personId:'p2',status:'invited'});f.api.executeBuy('o1','p2',150);assert.equal(f.db.portfolio.holdings[0].quantity,150);assert.notEqual(f.db.portfolio.holdings[0].batchId,f.db.portfolio.holdings[1].batchId)});
function documents(){const db={people:[],records:[],portfolio:{holdings:[]}};const ctx={pAvatar:()=>'<img alt="头像">',pCode:p=>p?.id||'',db,window:{},document:{addEventListener(){}},render(){}};vm.createContext(ctx);const src=fs.readFileSync('document-workspace.js','utf8').replace('setup();','globalThis.api={detect,speechCount};');vm.runInContext(src,ctx);return{db,api:ctx.api}}
for(const [text,kind] of [['我从来没有开过账户','开户'],['我从来没有加入过群','入群'],['我现在没有任何股票持仓','持仓']])test('recognizes denial: '+text,()=>{const f=documents(),p={id:'p1',account:{opened:true},crm:{joined_group:true}};f.db.portfolio.holdings.push({personId:'p1',status:'holding'});assert.ok(f.api.detect(p,text).some(x=>x.includes(kind)))});
test('repeated negative statement is not interpreted as positive trade history',()=>{const f=documents(),p={id:'p1'};f.db.records.push({personId:'p1',content:'从未参与过大宗交易'});assert.equal(f.api.detect(p,'我从没参与过大宗交易').filter(x=>x.includes('经历冲突')).length,0)});
test('bare editor text node resolves to editor block for number insertion',()=>{const editor={id:'dailyEditor'},text={nodeType:3,parentElement:editor};const ctx={pAvatar:()=>'<img alt="头像">',pCode:p=>p?.id||'',db:{people:[]},render(){},window:{getSelection:()=>({rangeCount:1,anchorNode:text})},document:{getElementById:()=>editor,addEventListener(){}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('document-workspace.js','utf8').replace('setup();','globalThis.api={currentBlock};'),ctx);assert.equal(ctx.api.currentBlock(),editor)});
test('holdings card includes quantity price currency and earliest sell time',()=>{const ctx={pAvatar:()=>'<img alt="头像">',pCode:p=>p?.id||'',db:{},person:()=>({name:'Test'}),pGender:()=>'',genderRelationLabel:()=>'',Date};vm.createContext(ctx);vm.runInContext(fs.readFileSync('trading-simulator.js','utf8').replace('setupUI();bindNav();','globalThis.api={renderBatches};'),ctx);const html=ctx.api.renderBatches([{key:'b',symbol:'DDD',currency:'USD',buyAt:'2026-09-29T00:00:00Z',rows:[{id:'h',quantity:150,buyPrice:65,plannedSellAt:'2026-10-02T00:00:00Z'}]}]);assert.match(html,/150/);assert.match(html,/65/);assert.match(html,/最早卖出/);assert.match(html,/USD/)});
for(const qty of [0,99,150.5,NaN])test('rejects invalid or below-minimum quantity '+qty,()=>{const f=trading();assert.equal(f.api.executeBuy('o1','p1',qty),false);assert.equal(f.db.portfolio.holdings.length,0)});
for(const price of ['', '-1','abc'])test('rejects empty or invalid sale price '+price,()=>{let submit;const hd={id:'h1',personId:'p1',symbol:'DDD',currency:'USD',quantity:150,buyPrice:65,buyAt:'2020-01-01',plannedSellAt:'2020-01-04',status:'holding'};const ctx={pAvatar:()=>'<img alt="头像">',pCode:p=>p?.id||'',db:{portfolio:{holdings:[hd],buyPlans:[]}},person:()=>({name:'test'}),pGender:()=>'',document:{querySelectorAll:()=>[{value:'h1'}]},openModal:(title,body,fn)=>{submit=fn},save(){},toast(){},setTimeout(){}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('trading-simulator.js','utf8').replace('setupUI();bindNav();','globalThis.api={openSellBatch};'),ctx);ctx.api.openSellBatch('h1');assert.equal(submit({get:()=>price}),false);assert.equal(hd.status,'holding')});
test('dashboard binding preserves people-table trade preference controls',()=>{
 const acorn=require('acorn'),src=fs.readFileSync('trade-dashboard.js','utf8');let fn;
 function walk(n){if(!n||typeof n!=='object')return;if(n.type==='FunctionDeclaration'&&n.id.name==='bindTradeActions')fn=src.slice(n.start,n.end);for(const v of Object.values(n)){if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object')walk(v)}}walk(acorn.parse(src,{ecmaVersion:'latest'}));
 const original=()=>{},button={onclick:original,closest:()=>({}),dataset:{tradePref:'p1'}};const ctx={pAvatar:()=>'<img alt="头像">',pCode:p=>p?.id||'',document:{querySelectorAll:s=>s==='[data-trade-pref]'?[button]:[]},byId:()=>null};vm.createContext(ctx);vm.runInContext(fn+';bindTradeActions()',ctx);assert.equal(button.onclick,original);
});
test('creating offers with identical clock timestamps still creates unique IDs',()=>{
 let submit;const db={people:[],tradeSim:{offers:[],recommendations:[]},portfolio:{holdings:[],buyPlans:[]}};
 class FixedDate extends Date{static now(){return 123456789}}
 const ctx={pAvatar:()=>'<img alt="头像">',pCode:p=>p?.id||'',db,Date:FixedDate,crypto:require('crypto').webcrypto,setTimeout(){},openModal:(t,b,fn)=>{submit=fn}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('trading-simulator.js','utf8').replace('setupUI();bindNav();','globalThis.api={editOffer};'),ctx);
 const data={symbol:'DDD',name:'DDD',currency:'USD',shares:'100',price:'65',days:'3',count:'10'};for(let i=0;i<2;i++){ctx.api.editOffer();submit({get:k=>data[k]||''})}assert.equal(db.tradeSim.offers.length,2);assert.notEqual(db.tradeSim.offers[0].id,db.tradeSim.offers[1].id);
});
